# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_type_0.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(442, 379)
        self.gridLayout_8 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridGroupBox_config = QtWidgets.QGroupBox(Dialog)
        self.gridGroupBox_config.setObjectName("gridGroupBox_config")
        self.gridLayout = QtWidgets.QGridLayout(self.gridGroupBox_config)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_config1 = QtWidgets.QLineEdit(self.gridGroupBox_config)
        self.lineEdit_config1.setObjectName("lineEdit_config1")
        self.gridLayout.addWidget(self.lineEdit_config1, 0, 3, 1, 1)
        self.lineEdit_config0 = QtWidgets.QLineEdit(self.gridGroupBox_config)
        self.lineEdit_config0.setObjectName("lineEdit_config0")
        self.gridLayout.addWidget(self.lineEdit_config0, 0, 1, 1, 1)
        self.label_config0 = QtWidgets.QLabel(self.gridGroupBox_config)
        self.label_config0.setObjectName("label_config0")
        self.gridLayout.addWidget(self.label_config0, 0, 0, 1, 1)
        self.label_config1 = QtWidgets.QLabel(self.gridGroupBox_config)
        self.label_config1.setObjectName("label_config1")
        self.gridLayout.addWidget(self.label_config1, 0, 2, 1, 1)
        self.label_config2 = QtWidgets.QLabel(self.gridGroupBox_config)
        self.label_config2.setObjectName("label_config2")
        self.gridLayout.addWidget(self.label_config2, 1, 0, 1, 1)
        self.label_config3 = QtWidgets.QLabel(self.gridGroupBox_config)
        self.label_config3.setObjectName("label_config3")
        self.gridLayout.addWidget(self.label_config3, 1, 2, 1, 1)
        self.lineEdit_config2 = QtWidgets.QLineEdit(self.gridGroupBox_config)
        self.lineEdit_config2.setObjectName("lineEdit_config2")
        self.gridLayout.addWidget(self.lineEdit_config2, 1, 1, 1, 1)
        self.lineEdit_config3 = QtWidgets.QLineEdit(self.gridGroupBox_config)
        self.lineEdit_config3.setObjectName("lineEdit_config3")
        self.gridLayout.addWidget(self.lineEdit_config3, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.gridGroupBox_config)
        self.gridGroupBox_OK = QtWidgets.QGroupBox(Dialog)
        self.gridGroupBox_OK.setObjectName("gridGroupBox_OK")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridGroupBox_OK)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.pushButton_Cancel = QtWidgets.QPushButton(self.gridGroupBox_OK)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.gridLayout_2.addWidget(self.pushButton_Cancel, 0, 3, 1, 1)
        self.pushButton_OK = QtWidgets.QPushButton(self.gridGroupBox_OK)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.gridLayout_2.addWidget(self.pushButton_OK, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 4, 1, 1)
        self.verticalLayout.addWidget(self.gridGroupBox_OK)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.gridLayout_8.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.gridGroupBox_config.setTitle(_translate("Dialog", "Config Value"))
        self.label_config0.setText(_translate("Dialog", "Config 0:"))
        self.label_config1.setText(_translate("Dialog", "Config 1:"))
        self.label_config2.setText(_translate("Dialog", "Config 2:"))
        self.label_config3.setText(_translate("Dialog", "Config 3:"))
        self.pushButton_Cancel.setText(_translate("Dialog", "Cancel"))
        self.pushButton_OK.setText(_translate("Dialog", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
